Merge ExecutionContext branch into PM-MascotParser trunk.
PM-MascotParser version is now 0.0.6-SNAPSHOT using Proline-Core 0.0.7-SNAPSHOT


Some tests FAIL because of "new UDS" merge :

org.dbunit.dataset.NoSuchTableException: IDENTIFICATION_FRACTION_SUMMARY

org.dbunit.dataset.NoSuchColumnException: PEPTIDE_PTM_INSERT_STATUS.ID -  (Non-uppercase input column: ID) in ColumnNameToIndexes cache map. Note that the map's column names are NOT case sensitive.

Tests in error: 
  runRFIwithSQLPepProviders(fr.proline.core.service.msi.RFImporterH2Test): IDENTIFICATION_FRACTION_SUMMARY
  runRFIwithJPA(fr.proline.core.service.msi.RFImporterH2Test): IDENTIFICATION_FRACTION_SUMMARY
  runRFIwithSQLPepProviders(fr.proline.core.service.msi.RFImporterSQLiteTest): PEPTIDE_PTM_INSERT_STATUS.ID -  (Non-uppercase input column: ID) in ColumnNameToIndexes cache map. Note that the map's column names are NOT case sensitive.
  runRFIwithJPA(fr.proline.core.service.msi.RFImporterSQLiteTest): PEPTIDE_PTM_INSERT_STATUS.ID -  (Non-uppercase input column: ID) in ColumnNameToIndexes cache map. Note that the map's column names are NOT case sensitive.


#7026